[2024-07-15T10:50:20.782+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-15T10:50:20.806+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-07-15T10:50:19.295534+00:00 [queued]>
[2024-07-15T10:50:20.815+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-07-15T10:50:19.295534+00:00 [queued]>
[2024-07-15T10:50:20.817+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-15T10:50:20.843+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): reddit_extraction> on 2024-07-15 10:50:19.295534+00:00
[2024-07-15T10:50:20.850+0000] {standard_task_runner.py:63} INFO - Started process 53 to run task
[2024-07-15T10:50:20.854+0000] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'etl_reddit_pipeline', 'reddit_extraction', 'manual__2024-07-15T10:50:19.295534+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/reddit_dag.py', '--cfg-path', '/tmp/tmpt3rampgo']
[2024-07-15T10:50:20.856+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask reddit_extraction
[2024-07-15T10:50:20.907+0000] {task_command.py:426} INFO - Running <TaskInstance: etl_reddit_pipeline.reddit_extraction manual__2024-07-15T10:50:19.295534+00:00 [running]> on host 24908e986cc7
[2024-07-15T10:50:21.009+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Indrajit Ghosh' AIRFLOW_CTX_DAG_ID='etl_reddit_pipeline' AIRFLOW_CTX_TASK_ID='reddit_extraction' AIRFLOW_CTX_EXECUTION_DATE='2024-07-15T10:50:19.295534+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-15T10:50:19.295534+00:00'
[2024-07-15T10:50:21.012+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-07-15T10:50:21.029+0000] {logging_mixin.py:188} INFO - connected to reddit!
[2024-07-15T10:50:21.452+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-07-15T10:50:21.453+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/pipelines/reddit_pipeline.py", line 17, in reddit_pipeline
    load_data_to_csv(post_df, file_path)
  File "/opt/airflow/etls/reddit_etl.py", line 52, in load_data_to_csv
    data.to_csv(path, index=False)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/core/generic.py", line 3967, in to_csv
    return DataFrameRenderer(formatter).to_csv(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/formats/format.py", line 1014, in to_csv
    csv_formatter.save()
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/formats/csvs.py", line 251, in save
    with get_handle(
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/common.py", line 749, in get_handle
    check_parent_directory(str(handle))
  File "/home/airflow/.local/lib/python3.9/site-packages/pandas/io/common.py", line 616, in check_parent_directory
    raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
OSError: Cannot save file into a non-existent directory: '/opt/airflow/data/output'
[2024-07-15T10:50:21.470+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=etl_reddit_pipeline, task_id=reddit_extraction, run_id=manual__2024-07-15T10:50:19.295534+00:00, execution_date=20240715T105019, start_date=20240715T105020, end_date=20240715T105021
[2024-07-15T10:50:21.511+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 3 for task reddit_extraction (Cannot save file into a non-existent directory: '/opt/airflow/data/output'; 53)
[2024-07-15T10:50:21.550+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-15T10:50:21.608+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-15T10:50:21.611+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
